# Generated by Django 4.2.5 on 2023-10-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0002_course_course_category_alter_tutor_expertise_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tutor.course_category",
            ),
        ),
    ]
