# Generated by Django 4.2.5 on 2023-10-02 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0003_alter_course_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="status",
        ),
    ]
