# Generated by Django 4.2.5 on 2023-10-04 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0004_remove_course_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tutor.course",
            ),
            preserve_default=False,
        ),
    ]
