# Generated by Django 4.2.5 on 2023-10-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0005_tutor_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
