# Generated by Django 4.1.7 on 2023-10-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0006_tutor_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video_upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("v_upload", models.CharField(blank=True, max_length=500, null=True)),
                ("up_time", models.DateTimeField()),
                ("desc", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="tutor",
            name="v_upload",
            field=models.ManyToManyField(to="tutor.video_upload"),
        ),
    ]
