# Generated by Django 4.1.7 on 2023-10-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0007_video_upload_tutor_v_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="v_upload",
            field=models.ManyToManyField(
                blank=True, null=True, to="tutor.video_upload"
            ),
        ),
    ]
