# Generated by Django 4.1.7 on 2023-10-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0008_alter_tutor_v_upload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Course_category",
        ),
    ]
