# Generated by Django 4.1.7 on 2023-10-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0009_remove_course_category_course_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.CharField(default="img", max_length=500),
        ),
    ]
