# Generated by Django 4.2.5 on 2023-10-17 19:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0014_video_upload_tutors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutor",
            name="v_upload",
        ),
        migrations.AlterField(
            model_name="video_upload",
            name="v_upload",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Video uploads"
            ),
        ),
    ]
