# Generated by Django 4.2.5 on 2023-10-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0018_alter_video_upload_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_structure",
            name="description",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
