# Generated by Django 4.2.5 on 2023-10-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0020_course_structure_levels_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course_structure",
            old_name="fees",
            new_name="price",
        ),
        migrations.AddField(
            model_name="course_structure",
            name="price_per",
            field=models.CharField(
                choices=[("Month", "Month"), ("Quarter", "Quarter"), ("Year", "Year")],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
    ]
