# Generated by Django 4.2.5 on 2023-10-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0021_rename_fees_course_structure_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Not Available", "Not Available"),
                ],
                default="Available",
                max_length=50,
            ),
        ),
    ]
