# Generated by Django 4.2.5 on 2023-11-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0023_alter_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="course-uploads"
            ),
        ),
    ]
