# Generated by Django 4.2.5 on 2023-11-14 07:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0017_taskupload"),
        ("tutor", "0024_alter_course_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Course_structure",
            new_name="CourseStructure",
        ),
        migrations.RenameModel(
            old_name="Resume_List",
            new_name="ResumeList",
        ),
        migrations.RenameModel(
            old_name="Video_upload",
            new_name="VideoUpload",
        ),
    ]
