# Generated by Django 4.2.5 on 2023-09-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="email",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="tutor",
            name="password",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="tutor",
            name="phone",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tutor",
            name="username",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
