# Generated by Django 4.2.5 on 2023-09-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_tutor_email_tutor_password_tutor_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(default=None, max_length=50)),
                ("phone", models.PositiveIntegerField()),
                ("password", models.CharField(default=None, max_length=50)),
                ("score", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="tutor",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
