# Generated by Django 4.2.5 on 2023-09-26 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_student_tutor_is_approved_alter_tutor_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tutor",
        ),
    ]
