# Generated by Django 4.2.5 on 2023-10-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_delete_tutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="student-images"),
        ),
    ]
