# Generated by Django 4.2.5 on 2023-11-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0010_sessionassign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionassign",
            name="video_link",
            field=models.CharField(default="video-link", max_length=200),
        ),
    ]
