# Generated by Django 4.2.5 on 2023-11-04 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0024_alter_course_image"),
        ("student", "0011_alter_sessionassign_video_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionassign",
            name="course_struct",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tutor.course_structure"
            ),
        ),
    ]
