# Generated by Django 4.2.5 on 2023-11-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0014_activityassign_delete_activitytask"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityassign",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("Pending", "Pending"),
                    ("Done Late", "Done Late"),
                ],
                default="Activity Task Assigned",
                max_length=50,
            ),
        ),
    ]
