# Generated by Django 4.2.5 on 2023-11-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0015_activityassign_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityassign",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("Pending", "Pending"),
                    ("Done Late", "Done Late"),
                    ("Activity Task Assigned", "Activity Task Assigned"),
                ],
                default="Activity Task Assigned",
                max_length=50,
            ),
        ),
    ]
