# Generated by Django 4.2.5 on 2023-11-14 07:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0016_alter_activityassign_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_upload",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Task uploads",
                    ),
                ),
                ("up_time", models.DateTimeField()),
                ("description", models.CharField(max_length=220)),
                (
                    "student",
                    models.ManyToManyField(
                        blank=True, related_name="tasks", to="student.student"
                    ),
                ),
            ],
        ),
    ]
