# Generated by Django 4.2.5 on 2023-11-14 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0017_taskupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskupload",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.activityassign",
            ),
        ),
    ]
