# Generated by Django 4.2.5 on 2023-11-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0018_taskupload_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityassign",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("Pending", "Pending"),
                    ("Done Late", "Done Late"),
                    ("Task Assigned", "Task Assigned"),
                ],
                default="Task Assigned",
                max_length=50,
            ),
        ),
    ]
